name: 'Spectral Control'

on:
  push:
    branches:
    - "main"

env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs:      
  spectral-pipeline:
    name: 'Spectral Security Control'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Spectral Setup & Scan
      uses: spectralops/spectral-github-action@v2
      with:
        spectral-dsn: ${{ secrets.SPECTRAL_DSN }}
        spectral-args: scan --ok --include-tags base,audit,iac --table
